- config: 
    delay: 
        mode: inherited # inherited or default
        value: 1000 # default delays - 1sec
    template:
        path: template.groovy # relative path to template
        time_base: milliseconds # not used anywhere, just for reference
    database:
        path: example.db # relative path to template
        table_name: LOG_MESSAGES
        mandatory_fields:
            - simulationTime
            - message
            - senderName

- query:
    description: "Identifies TC processed successfuly by the TcDecoder and writes command to inject TC directly"
    sql: >
        SELECT rowId, simulationTime, message 
        FROM LOG_MESSAGES WHERE senderName LIKE '%TcDecoder%' AND
        message LIKE '%TC segment received%'
    regex: '(?<=\breceived: \s).*'
    script: |
        Scheduler.SimTimeWait(<DELAY>);
        TcDecoder.InjectSegment("<ARG>");

- query:
    description: "Identifies the breakpoint used and writes command to loads the breakpoint"
    sql: >
        SELECT rowId, simulationTime, message
        FROM LOG_MESSAGES WHERE senderName LIKE 'Storer' AND
        message LIKE 'Loading breakpoint from file%'
    regex: '(?<=\bfile\s).*'
    script: |
        Scheduler.SimTimeWait(<DELAY>);
        Storer.LoadBreakpoint("<ARG>");
